{"version":2,"defects":{"Tests\\Unit\\RouterTest::test_it_registers_a_post_route":7,"Tests\\Unit\\RouterTest::test_there_are_no_routes_when_router_is_created":8,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception":8,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #3":7,"Tests\\Unit\\RouterTest::test_it_resolve_route_from_a_closure":7},"times":{"Tests\\Unit\\RouterTest::test_it_registers_a_route":0.012,"Tests\\Unit\\RouterTest::test_that_it_registers_a_route":0,"Tests\\Unit\\RouterTest::test_it_registers_a_get_route":0,"Tests\\Unit\\RouterTest::test_it_registers_a_post_route":0,"Tests\\Unit\\RouterTest::test_there_are_no_routes_when_router_is_created":0,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception":0.026,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #0":0.003,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #3":0,"Tests\\Unit\\RouterTest::test_it_resolve_route_from_a_closure":0.024}}